### ISSUE TITLE
restart-emacs on win32 doesn't use correct process

### ISSUE THREAD

**Issue by wallacewinfrey** [iqbalansari/restart-emacs#2] opened 2015-12-02 22:45 UTC
I'm trying to use `restart-emacs` with win32 emacs (specifically, `GNU Emacs 25.0.50.1 (x86_64-w64-mingw32)`) and the process is not restarting the correct emacs binary.

I use the **`runemacs.exe`** binary to launch emacs, not the regular **`emacs.exe`**. Unfortunately, it looks like function that gets the *"absolute path to binary of currently running Emacs"*, `restart-emacs--get-emacs-binary` doesn't get the right binary name due to the fact that **`runemacs.exe`** is, I believe, a launcher program that forks off **`emacs.exe`** in a specific mode and exits.

Would it be possible to make this a user-definable value? I did try removing the console window with **`editbin.exe`** ([as mentioned in this reddit post](https://www.reddit.com/r/emacs/comments/2rvjv7/runemacsexe_on_windows/)) but **`editbin.exe`** wouldn't open the file (maybe because it was built with mingw? I dunno).

**Comment by iqbalansari** [comment] 2015-12-03 03:13
Thanks for the bug report. I would prefer user does not need to do any additional setup for this to work, let me research a bit and see if I can automatically handle this case otherwise I would add a user-definable value.

**Comment by iqbalansari** [comment] 2015-12-03 16:03
Thinking of it, I think `restart-emacs` can always use `runemacs.exe` on Windows. is there is any use case for using `emacs.exe` instead of `runemacs.exe`?

**Comment by iqbalansari** [comment] 2015-12-03 16:42
I have pushed a commit to always use `runemacs.exe` on Windows. Please try it when MELPA builds and report back.

**Comment by iqbalansari** [comment] 2015-12-05 17:04
Hi,

I am closing this, feel free to reopen if you think the issue is not resolved

Thanks

**Closed by iqbalansari** 2015-12-05 17:04 UTC
